# Generated by Django 3.0.8 on 2020-10-13 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfbrakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfTide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('date', models.DateTimeField()),
                ('surfbrake', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surfbrakes.Surfbrake')),
            ],
        ),
    ]
