# Generated by Django 3.0.8 on 2020-10-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfbrakes', '0002_surftide'),
    ]

    operations = [
        migrations.AddField(
            model_name='surftide',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
