# Generated by Django 3.0.8 on 2020-10-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfbrakes', '0003_surftide_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfbrake',
            name='wave_height_avg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surfbrake',
            name='wave_height_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surfbrake',
            name='wave_height_min',
            field=models.TextField(blank=True, null=True),
        ),
    ]
