# Generated by Django 3.0.8 on 2020-08-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webcrawler',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_url', models.TextField()),
                ('site_endpoint', models.TextField()),
                ('item', models.TextField(max_length=100)),
                ('availability', models.TextField(max_length=100)),
                ('search_object_regex', models.TextField()),
                ('search_object_value', models.TextField()),
                ('search_object_property_list', models.TextField()),
                ('search_object_property_availability', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
