# Generated by Django 3.0.8 on 2020-08-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcrawler',
            name='site_name',
            field=models.TextField(default='site-name', max_length=100),
        ),
    ]
