# Generated by Django 3.0.8 on 2020-08-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webcrawlers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('webcrawlers', models.ManyToManyField(blank=True, to='webcrawlers.Webcrawler')),
            ],
        ),
    ]
